---
- hosts: all

  become: true
  tasks:
    - name: update apt packages
      apt:
        update: yes
        
    - name: upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes